### ISSUE TITLE
Remove Google-Analytics

### ISSUE THREAD

**Issue by der-On** [Leipziger-Ecken/drupal#14]
In favor of a GDPR friendly and privacy respecting alternative like matomo or plausible.io Google-Analytics should be removed.

**Comment by der-On** [comment]
@FlxAlbroscheit I would like your feedback on this.

**Comment by der-On** [comment]
@FlxAlbroscheit any news on this? I find it difficult to rely on a privacy harrasing tool like GA with a publicly funded project.

**Comment by FlxAlbroscheit** [comment]
I will set up and integrate matomo as soon as we have mastered to merge the website builder. Matomo provides a neat [Google Analytics importer](https://matomo.org/docs/google-analytics-importer/) that I'm gonna use here.

**Comment by der-On** [comment]
Then I will remove GA module from the dev branch.
