### ISSUE TITLE
Remove ReCaptcha

### ISSUE THREAD

**Issue by der-On** [Leipziger-Ecken/drupal#15]
In favor of a GDPR friendly and privacy respecting and more accessible alternative, Googles ReCaptcha should be removed.

Google ReCaptcha is not accessible by any means, does track users and is mainly used to train Google-AI tech.

Possible alternatives are Math-Captchas or hCaptcha.

**Comment by der-On** [comment]
@FlxAlbroscheit I would like your thoughts on this.

**Comment by FlxAlbroscheit** [comment]
Hi @der-On, I totally agree! I have checked hCaptcha and ensured that it is running as expected.

Btw, how should we handle API keys in the future, do you know any best practices from the Drupal-/Symfony-context? In my api-import-module I imported API-keys from sites/default/settings.php, but a better way would probably be to use an .env-file and reference it in the .yml-configurations? Do you know if that is possible?

**Comment by der-On** [comment]
Yes, using .env files is totaly possible in drupal. https://www.drupal.org/project/env_variables
The current solution I have is to have settings.php contain default settings and a settings.local.php (ignored by git) containing custom settings for the environment and sensitive data. https://github.com/Leipziger-Ecken/drupal/blob/develop/src/drupal/web/sites/default/settings.php#L797
