### ISSUE TITLE
Remove rules module?

### ISSUE THREAD

**Issue by der-On** [Leipziger-Ecken/drupal#19]
The rules module in it's current state causes problems with visibility options for blocks and other things in core.

Looking through the code I found out it is used in the custom le_website module, but only for a deactivated rules component.
For what exactly is rules used currently and can it be removed and replaced by using Drupals event system?

**Comment by FlxAlbroscheit** [comment]
Moin! You are completely right, there is no need for rules anymore and we can (should!) remove it. I was once trying to create a rules-based workflow to extend the organic groups module (e.g. "Send a mail to the group owners when a membership is requested"), but I failed as some mandatory tokens were not yet provided by OG.

**Comment by der-On** [comment]
How good, that I've just removed it today in the develop branch.
