### ISSUE TITLE
Registrierungsprobleme Mailversand 

### ISSUE THREAD

**Issue by videomatze** [Leipziger-Ecken/drupal#20]
Anmeldefunktion: Bei der Registrierung als neuer Nutzer muss darauf hingewiesen werden das eine Mail verschickt wurde, im Mailpostfach /Spamorder nachschauen soll.
Vorschlag: "Sie haben jetzt eine E Mail erhalten und können über den in der Mail enthaltenen Link sich einmal amelden und ein Passwort vergeben. Damit wäre ihre Registrierung dann abgeschlossen. Wenn sie keine Mail erhalten haben klicken sie bitte hier."

**Comment by FlxAlbroscheit** [comment]
Der Text mit Hinweis auf Spamordner wurde bereits geändert, fälschlicherweise aber nicht auf der Startseite (erst bei klick auf Unterseite nach erfolgter Registrierung) angezeigt. Ist nun gelöst und live.
