### ISSUE TITLE
Caching of le_admin routes

### ISSUE THREAD

**Issue by der-On** [Leipziger-Ecken/drupal#28]
@FlxAlbroscheit I'm currently struggling with the aggressive caching in the le_admin routes for authenticated users.
Drupal is caching node displays and breadcrumbs. Disabling cache using the route option `no_cache: true` and using `#max-age => 0` in the controller code does not help as the node and breadcrumb level cache hits here.

I guess the solution is to add a cachable context to the breadcrumb and to somehow disable the caching of the nodes at least in the backend_teaser view modes.

**Comment by FlxAlbroscheit** [comment]
I never really dealt with drupal caching in custom modules :( Have you been able to solve the problem?

**Comment by der-On** [comment]
Currently I wasn't able to fix the caching issues. I will now try to adjust caching for the views used, however the breadcrumb caching requires a caching context.

**Comment by der-On** [comment]
fixed it in https://github.com/Leipziger-Ecken/drupal/commit/2ea840057b5fa1900acf703467f6db45ee8700d9
