### ISSUE TITLE
@todos

### ISSUE THREAD

**Issue by FlxAlbroscheit** [Leipziger-Ecken/drupal#3]
Memo an mich selbst:
- [x] /akteure & /events -> URI-Slug automatisch beim speichern generieren: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21entity.api.php/function/hook_ENTITY_TYPE_presave/9.0.x
- [x]  Karte: Idealen Map-Typ für nachbarschaftliche/lokale Zwecke finden (z.B. https://www.thunderforest.com/maps/neighbourhood/), integrieren via https://www.drupal.org/project/leaflet_more_maps
- [x]  "Feature UI" & "Menu UI" als dependency aufnehmen
- [x] Events: Eigene Ansicht/Widget für wiederkehrende Events (auf [dieser](https://www.drupal.org/project/date_recur_modular) Basis)
- [ ] Default Verknüpfungen in Administrations-toolbar anlegen: Alle Events | Events anlegen | Regionen | Bezirke , etc.
- [x] [Sitemap-Modul](https://www.drupal.org/project/simple_sitemap)
- [ ] Metatag/Schema für Inhaltstyp Artikel anlegen
- [ ] Ggf.: [Rules-Modul](https://www.drupal.org/project/rules) (autom. Versand von Akteur-angelegt-Mails an Admin/Stadtteil; Benachrichtigungen nach Speichern von Daten; autom. Versand von Akteur-unvollständig-Mails bei Akteuren ohne klare Tags/Kategorien; Gruppenmitgliedsanfragen und -bestätigungen)
- [ ] Golden goal: [Symfony local server](https://www.oliverdavies.uk/blog/running-drupal-88-symfony-local-server) einrichten, dokumentieren und ggf. in Makefile funktionalisieren. Alternative: Docker-basiertes [Lando](https://lando.dev/).
- [x] Alias Formulare
- [x] Vor Release 0.3 le_comments mit default comments-feature-export mergen um Installationsprozess wiederherzustellen.
- [x] Fullcalendar entfernen (n. mit wiederkehrenden Events kompatibel :( )
- [ ] Eigenen Benutzernamen ändern als Berecht. setzen

**Comment by alex-brade** [comment]
- [ ] Startseite: Journalbeiträge: Überschriften mal in gleicher Schriftgröße wie bei Events und Akteuren ausprobieren. 
- [ ] Startseite: Journalbeiträge: Vorschautext möglich auf z.B. 100 Zeichen zu limitieren?
- [ ] Startseite: Große Icons vor Akteure, Events und Journal --> möglich?
- [ ] Footer: anderes Logo: https://drive.google.com/file/d/1rsRH871OHe6r3d54QkL8_wBQyPAruqw9/view?usp=sharing 
- [ ] Footer: 2-Spaltigkeit in der Auflistung ausprobieren (2x3)

**Comment by walthierer** [comment]
> **grafische to-do's**:
> 
>     * [x]  Startseite: Journalbeiträge: Überschriften mal in gleicher Schriftgröße wie bei Events und Akteuren ausprobieren.
> 
>     * [x]  Startseite: Journalbeiträge: Vorschautext möglich auf z.B. 100 Zeichen zu limitieren?
>              change under _structure/types/manage/article/display/teaser_ >> Textkörper >> Settings (Zahnradicon) >> Maximale Anzahl von Zeichen im Anrisstext
>     * [ ]  Startseite: Große Icons vor Akteure, Events und Journal --> möglich?
> 
>     * [ ]  Footer: anderes Logo: https://drive.google.com/file/d/1rsRH871OHe6r3d54QkL8_wBQyPAruqw9/view?usp=sharing
> 
>     * [ ]  Footer: 2-Spaltigkeit in der Auflistung ausprobieren (2x3)



> **grafische to-do's**:
> 
>     * [x]  Startseite: Journalbeiträge: Überschriften mal in gleicher Schriftgröße wie bei Events und Akteuren ausprobieren.
> 
>     * [x]  Startseite: Journalbeiträge: Vorschautext möglich auf z.B. 100 Zeichen zu limitieren?
> 
>     * [ ]  Startseite: Große Icons vor Akteure, Events und Journal --> möglich?
> 
>     * [ ]  Footer: anderes Logo: https://drive.google.com/file/d/1rsRH871OHe6r3d54QkL8_wBQyPAruqw9/view?usp=sharing
> 
>     * [ ]  Footer: 2-Spaltigkeit in der Auflistung ausprobieren (2x3)
