### ISSUE TITLE
Webbaukasten läuft nicht

### ISSUE THREAD

**Issue by videomatze** [Leipziger-Ecken/drupal#70]
Hey Felix, Thomas
ich kann nicht am Webbaukasten arbeiten.
Er ist wieder nicht richtig funktiostüchtig. Ich kann immer nur den Seitentitel bearbeiten. Weiter geht es nicht.

Hier mal die Meldung: https://leipziger-ecken.de/user/webbuilder/4535/pages

The website encountered an unexpected error. Please try again later.
Error: Call to a member function getTitle() on null in Drupal\le_admin\Breadcrumb\BreadcrumbBuilder->build() (line 171 of modules/custom/le_admin/src/Breadcrumb/BreadcrumbBuilder.php).

Drupal\le_admin\Breadcrumb\BreadcrumbBuilder->build() (Line: 83)
Drupal\Core\Breadcrumb\BreadcrumbManager->build() (Line: 72)
Drupal\system\Plugin\Block\SystemBreadcrumbBlock->build() (Line: 171)
Drupal\block\BlockViewBuilder::preRender()
call_user_func_array() (Line: 100)
Drupal\Core\Render\Renderer->doTrustedCallback() (Line: 781)
Drupal\Core\Render\Renderer->doCallback() (Line: 372)
Drupal\Core\Render\Renderer->doRender() (Line: 444)
Drupal\Core\Render\Renderer->doRender() (Line: 200)
Drupal\Core\Render\Renderer->render() (Line: 501)
Drupal\Core\Template\TwigExtension->escapeFilter() (Line: 64)
__TwigTemplate_74225503b15b008a80afcfe1ea6d28a1cb9888cfbf9c064896b20c3154875550->doDisplay() (Line: 455)
Twig\Template->displayWithErrorHandling() (Line: 422)
Twig\Template->display() (Line: 434)
Twig\Template->render() (Line: 64)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 431)
Drupal\Core\Render\Renderer->doRender() (Line: 200)
Drupal\Core\Render\Renderer->render() (Line: 501)
Drupal\Core\Template\TwigExtension->escapeFilter() (Line: 102)
__TwigTemplate_36acfdb3c7ad33d00b68de327969db7a6d566328ece0cd01eb3dcfcef24fef85->doDisplay() (Line: 455)
Twig\Template->displayWithErrorHandling() (Line: 422)
Twig\Template->display() (Line: 434)
Twig\Template->render() (Line: 64)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 431)
Drupal\Core\Render\Renderer->doRender() (Line: 200)
Drupal\Core\Render\Renderer->render() (Line: 147)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext() (Line: 148)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse() (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray()
call_user_func() (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() (Line: 156)
Symfony\Component\HttpKernel\HttpKernel->handleRaw() (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle() (Line: 57)
Drupal\Core\StackMiddleware\Session->handle() (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle() (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass() (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle() (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() (Line: 49)
Drupal\remove_http_headers\StackMiddleware\RemoveHttpHeadersMiddleware->handle() (Line: 23)
Stack\StackedHttpKernel->handle() (Line: 708)
Drupal\Core\DrupalKernel->handle() (Line: 19)

**Comment by videomatze** [comment]
Weiterer Hinweis...es lassen sich nur Titel der Seiten erstellen. Ich kann keine weiteren Bearbeitungsschritte tun.

**Comment by der-On** [comment]
Leider habe ich keinen SSH Zugriff auf den Serve,r, so dass ich nicht konkret nach Fehlern suchen kann, aber nach einem Blick in die Feldkonfiguration sehe ich, dass fast alle Felder in den Bearbeitungsformularen deaktiviert sind. Als ob die Konfiguration nicht korrekt importiert wurde. Gleiches gilt für die Ansichten von Inhalten. Hier scheint beim deployment irgendetwas nicht funktioniert zu haben.

@FlxAlbroscheit kannst du bitte nochmal prüfen, ob die configs korrekt importiert wurden? Vielen Dank.

**Comment by FlxSaenger** [comment]
Hallo @der-On, die "Formularanzeige" für Blog & Webbaukasten wurde seinerzeit korrekt importiert, da ja auch schon einige Baukästen angelegt wurden. Warum die Felder deaktiviert wurden, ist mir ein Rätsel. Habe die fehlerbehafteten Konfigurationen über die UI wieder importiert und es geht.
