### ISSUE TITLE
NORDEN/OSTEN

### ISSUE THREAD

**Issue by videomatze** [Leipziger-Ecken/drupal#9]
Leider ist die Nutzerführung unverständliche..die Markierung der Landigpages sollt weiterhin erhalten bleiben bis ich mich aus dem Norden örtlich rausbewege..also sobald ich mir mehr Inhalte anzeigen lasse. Bis dahin sollte es markiert sein ob ich Norden oder Osten suche. 
![grafik](https://user-images.githubusercontent.com/670945/101776269-f6140000-3af0-11eb-840a-972268fb3c99.png)

Vielleicht kann man auch eine dritte Farbe dafür nehmen...leer, dunkelblau bei Mouseover und hellblau wenn markiert.

**Comment by FlxAlbroscheit** [comment]
Hi @videomatze! Also Du meinst, dass man bspw. beim Besuchen eines Akteur- oder Eventprofils, welches einem Bezirk aus der Region "Norden" oder "Osten" zugeteilt ist, dies auch entsprechend an der Stadtregionen-Navigation links sichtbar wird? Bzw. dann auch bei einem Journal-Artikel, der einer der Regionen zugeteilt ist?

Wäre auf jeden Fall denkbar.

**Comment by FlxAlbroscheit** [comment]
Hi @videomatze, ich habe eine Entwicklung eingeschoben, die bei Akteur-, Event- und Journal-Detailseiten das jeweilige Stadtregion-Navigationselement markiert, welches jeweils gerade im Kontext steht. Ebenso werden jetzt auf den Detailseiten ebenso die Hauptmenü-Punkte als aktiv markiert. 

Ist das Problem damit für Dich gelöst? Wenn ja, bitte Ticket schließen!
